import type { Metadata } from "next"
import { Noto_Serif } from "next/font/google"

import { TRPCReactProvider } from "@/trpc/client"

import "./globals.css"

const notoSerif = Noto_Serif({
	subsets: ["latin"],
	variable: "--font-noto-serif",
	weight: ["300", "700"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<TRPCReactProvider>
			<html lang="en">
				<body className={`${notoSerif.className} antialiased`}>{children}</body>
			</html>
		</TRPCReactProvider>
	)
}
